spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: ${dbconnectionstring}
spring.datasource.password: ${dbpassword}
spring.datasource.username: ${dbusername}

server:
  port : ${sb_listeningport}

#logging:
#  path: /var/log
#logging:
#  file: ijf.log

spring:
  thymeleaf:
    prefix: classpath:/templates
  datasource:
    hikari:
      minimum-idle: ${dbminidle}
      maximum-pool-size: ${dbmaxpoolsize}
      connection-timeout: ${dbconnectiontimeout}

addon:
  key: com-idealfed-forms-worklogs
  base-url: ${baseurl}

ijfRoot: /

atlassian.connect.jwt-expiration-time: ${jwtexpirationtime}

atlassian.connect.self-authentication-expiration-time: ${selfauthexpirationtime}
#atlassian.connect.allow-reinstall-missing-host: true

logging.level.com.atlassian.connect.spring: ${springloglevel}

logging.level.com.idealfed.forms.DataController: ${ifdataloglevel}
logging.level.com.idealfed: ${ifdataloglevel}

atlassian:
  connect:
    redirect-root-to-descriptor: false


