spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:hsqldb:file:ijfdb_20 # Use a file-based backing store for HSQL
spring.datasource.password: dogland
spring.datasource.username: SA

server:
  port : 8080

#logging:
#  path: /var/log
#logging:
#  file: ijf.log

spring:
  thymeleaf:
    prefix: classpath:/templates

addon:
  key: com-idealfed-forms20
  base-url: https://www.idealfed.com/dev20

ijfRoot: /dev20

#atlassian.connect.allow-reinstall-missing-host: true

logging.level.com.atlassian.connect.spring: DEBUG

logging.level.com.idealfed.forms: DEBUG

atlassian:
  connect:
    jwt-expiration-time: 86400



