spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:hsqldb:file:ijfdb_6 # Use a file-based backing store for HSQL
spring.datasource.password: dogland
spring.datasource.username: SA

addon:
  key: com-idealfed-forms3
  base-url: https://www.idealfed.com/dev5

#atlassian.connect.allow-reinstall-missing-host: true

logging.level.com.atlassian.connect.spring: DEBUG

logging.level.com.idealfed.forms.DataController: DEBUG




